### ISSUE TITLE
css居中

### ISSUE THREAD

**Issue by libersand** [libersand/blogs#4]
### 水平居中
```css
.block{
 margin: 0 auto
}
```
#### 已知高度
```css
.blockWrapper{
    position: relative;
}
.block{
   position: absolute;
   top: 50%;
   heigth: 100px;
   margintop: -50px;
}
```
#### 未知高度
```css
.blockWrapper{
    position: relative;
}
.block{
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
}
```
### 水平居中
```css
.div{
   text-align: center;
}
```
### 垂直居中
通过设置line-height与height相等
```css
.div{
  height: 100px;
  line-height: 100px;
}
```
### 有固定的宽高
```css
.parent {
    position: relative;
}
.child { 
    box-sizing: border-box;
    width: 100px;
    height: 100px;
    position: absolute;
    top: 50%;
    left: 50%;
    margin: -50px 0 0 -50px;
}
```
### 没有固定的宽高
```css
.parent{
    position: relative;
}
.child {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50% -50%);
}
```
