### ISSUE TITLE
:nth-child()的使用

### ISSUE THREAD

**Issue by libersand** [libersand/blogs#6]
```css
el:nth-child(2) {} //选取el的第二个标签
el:nth-child(n+3) {} //选取el的大于等于3的标签
```
例子：
```html
<div class="bouncing-loader">
  <div></div>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
</div>
```
```css

.bouncing-loader {
  display: flex;
  justify-content: center;
}
.bouncing-loader > div:nth-child(1) {
  width: 2rem;
  height: 2rem;
  border: 2px solid black;
  background-color: blue;
}
.bouncing-loader > div:nth-child(2) {
  width: 2rem;
  height: 2rem;
  border: 2px solid black;
  background-color: gray;
}
.bouncing-loader > div:nth-child(n+3) {
  width: 2rem;
  height: 2rem;
  border: 2px solid black;
  background-color: red;
}
```
结果：
![image](https://user-images.githubusercontent.com/30036938/56255138-4f4a4700-60f6-11e9-8745-fca68b48432c.png)
