### ISSUE TITLE
被margin/padding伤害

### ISSUE THREAD

**Issue by libersand** [libersand/blogs#7]
margin/padding 都可以用来留出空白，但是两者的含义却有点不同。
* margin表示元素与元素之间的距离
* padding表示一个元素content与border之间的距离

margin会出现垂直外边距合并，在垂直方向上如果两个元素同时指定了上下外边距，那么这两个元素之间的margin是两个margin中较大的一个，来看一个例子吧。
```html
<div class="container">
  <div>
    我是盒子一  
  </div>
  <div>
    我是盒子二
  </div>
</div>
```
```css
.container > div:nth-child(1){
  width: 200px;
  height: 100px;
  line-height: 100px;
  text-align: center;
  border: 1px solid;
  margin:0px 0px 100px 0px;
}
.container > div:nth-child(2){
  width: 200px;
  height: 100px;
  line-height: 100px;
  text-align: center;
  border: 1px solid;
  margin: 100px 0px 0px 0px;
}
```
结果：
![image](https://user-images.githubusercontent.com/30036938/56271620-7838ff00-612b-11e9-8cad-ddfbe7dc8e8c.png)

同样margin的颜色是透明的，他的颜色会根据父级的backg-color而定，padding的颜色可以有当级元素的bzckground-color而定。
