### ISSUE TITLE
负margin的使用

### ISSUE THREAD

**Issue by libersand** [libersand/blogs#8]
结论： 当margin值为负的时候，top\left使自身元素移动，bottom\right使其下\右的元素移动，
看一个例子吧：
```html
<div class="wrap">
  <div class="num1">我的right有-10px</div>
  <div class="num2">我的bottom有-10px</div>
  <div class="num3">我的top有-10px</div>  
  <div class="num4">我的left有-10px</div>
</div>
```
```css
*{
  margin:0; 
  padding:0;
}
.wrap{
  width:440px; 
  border:10px solid #000;
  display: flex;
  flex-wrap: wrap;
}
.wrap > div {
  box-sizing: border-box;
  width: 200px;
  height: 100px;
  line-height: 90px;
  text-align: center;
}
.num1{
  border: 5px solid red;
  margin-right: -10px;
}
.num2 {
  border: 5px solid green;
  margin-bottom: -10px;
}
.num3{
  border: 5px solid blue;
  margin-top: -10px;
}
.num4{
  border: 5px solid yellow;
  margin-left: -10px;
}
```
结果：
![image](https://user-images.githubusercontent.com/30036938/56276538-4167e680-6135-11e9-98c9-e4fdd56491ed.png)

num2的负值margin-bottom为什么不起作用呢，这是一个需要注意的问题。
参考文章：[我知道你不知道的负Margin](http://www.hicss.net/i-know-you-do-not-know-the-negative-margin/)
